### ISSUE TITLE
Invert Colors ?

### ISSUE THREAD

**Issue by fastrizwaan** [ErwanDouaille/gse-shader#1]
Please add invert colors to gse-shader, that would make reading more fun. Current we have to depend on xcalib -i -a

Thanks.

**Comment by ErwanDouaille** [comment]
I just add it. Let me know if it's correspond to your needs ;)

**Comment by fastrizwaan** [comment]
thank you, it works as expected, but I can't combine luminosity with invertColors. We can only use 1 shader at a time. 

It would be great, if we could have both brightness (luminosity) and color inversion together. 

Thanks.
