### ISSUE TITLE
medianFilter hangs gnome-shell in fedora 23

### ISSUE THREAD

**Issue by fastrizwaan** [ErwanDouaille/gse-shader#3]
cpu usage goes up to 81% and the shell becomes unresponsive, must have to kill gnome-shell and delete the mediafilter.frag file. Please look into the issue with medianFilter on Fedora 23 Xorg.

**Comment by ErwanDouaille** [comment]
I know this one is a bit weird, that's the reason why i didn't push it on the gnome-extension website. One of my teammate had the same issue. On my machines (GTX 770 or Quadro K2000) it works well ... I have to investigate.

What is your GPU ?

PS: In case of crash type: alt + f2    then    r    then enter. It will "replace" gnome-shell

**Comment by frantisekz** [comment]
Yep, same issues began to show up after enabling gse-shader.

100% reproducible on lock screen (unresponsive after unlock, mouse moves but nothing else) - you have to press alt + f2 , switch to different vt and back again, type "r" enter, wait while and you're unstuck.
Apart from that I am experiencing random unrecoverable freezes (not possible to reproduce).

Intel HD 4400 (Haswell), Fedora 23 + updates-testing

**Comment by ErwanDouaille** [comment]
> 100% reproducible on lock screen (unresponsive after unlock, mouse moves but nothing else) - you have to press alt + f2 , switch to different vt and back again, type "r" enter, wait while and you're unstuck.

In blind mode, just type alt + f2 then r  and enter. Works for me.

> Apart from that I am experiencing random unrecoverable freezes (not possible to reproduce).

Same problem here, even if i´m not using gse-shader extension. Is it related with gse-shader on your machine ?

> Intel HD 4400 (Haswell), Fedora 23 + updates-testing

Tested with GTX770, Quadro K2000, Quadro FX4600. All of them running nouveau driver. Fedora 23 + updates-testing.

**Comment by frantisekz** [comment]
> Same problem here, even if i´m not using gse-shader extension. Is it related with gse-shader on your machine ?

I thought it was related to gse-shader extension but I had disabled it yesterday and today I got stuck after starting Steam client (but I was able to somehow get unstuck thanks to angrily spamming alt + f2 and r :) ). These freezes happen often in Steam client.

I am not sure if extension can do this freezes even if it's disabled. I don't think so, this might be a bug in GNOME/Free drivers stack.

**Comment by ErwanDouaille** [comment]
> I am not sure if extension can do this freezes even if it's disabled. I don't think so, this might be a bug in GNOME/Free drivers stack.

If the extension is disabled in gnome-tweak-tool and you restarted the gnome-shell, it might not be related to the extension.

**Comment by ErwanDouaille** [comment]
Does this bug is still present on F24/F25 ?
