### ISSUE TITLE
Remember settings for each shader

### ISSUE THREAD

**Issue by fastrizwaan** [ErwanDouaille/gse-shader#4]
If we set the slider for say Luminosity to 50% and then swittch to other shader like magnifier, the magnifier also runs at 50%, now if we again change magnifier to 10% and switch to Luminosity, the screen becomes 10% luminous. This means, settings every shader gets same settings from slider.

Please consider, settings for each shader. Thanks.

**Comment by ErwanDouaille** [comment]
Yep, same problem here. I updated another repository ... Each time you will change shader, the slider will be reset to 50%. I will push it today.

**Comment by ErwanDouaille** [comment]
Commit: https://github.com/ErwanDouaille/gse-shader/commit/856cf2192d7e81e9712a6727d849d874d28b349a
