### ISSUE TITLE
luminosity - 0% = black screen

### ISSUE THREAD

**Issue by fastrizwaan** [ErwanDouaille/gse-shader#5]
If we set slider to 0% and switch to luminosity shader, then the screen becomes totally black, We can't see the shadermenu or slider, this becomes problematic, the user can't work or change shader settings again.

Please do not allow less than say 5% luminosity. Thanks.

**Comment by ErwanDouaille** [comment]
Oops didn't push on the correct repository. I already fix this issue, i will update this git with another repository with a correct version.

Sorry

**Comment by ErwanDouaille** [comment]
Commit https://github.com/ErwanDouaille/gse-shader/commit/2ddcd4a3f1037f24836c10c091ccfbb5a5b4f0e8
