### ISSUE TITLE
Separate icon for each shader on gnome-shell top bar

### ISSUE THREAD

**Issue by fastrizwaan** [ErwanDouaille/gse-shader#6]
As a visual indicator to the active shader in use, please have icons at topbar in place of GLSL text for each shader, for example,  (just a hint)

luminosity - a light bulb
magnifying glass for magnifier shader
Negative icon for invertcolors
mousepointer with crosshairs for mousetracker
color flower for pixelColorization

Thanks.

**Comment by ErwanDouaille** [comment]
Commit https://github.com/ErwanDouaille/gse-shader/commit/17ae2a8ae3841385b148b941afbcaddf9a74b397 not set in master branch. Not sure if it's a good idea. 

You can test with magnifier, mouseTracker, pixelColoration.
